class UK3CB_B_Knapsack_Blk;
class UK3CB_TKP_O_B_ASS_BLK: UK3CB_B_Knapsack_Blk {
    mass = 20;
    maximumLoad = 160;
};
class UK3CB_CPD_B_B_ASS_BLU: UK3CB_B_Knapsack_Blk {
    mass = 20;
    maximumLoad = 160;
};

#define ASSAULT(type)\
class type: B_AssaultPack_rgr {\
    maximumLoad = 160;\
}

class B_AssaultPack_rgr;
ASSAULT(UK3CB_B_AssaultPack_DPM_68);
ASSAULT(UK3CB_B_AssaultPack_DPM_85);
ASSAULT(UK3CB_B_AssaultPack_DPM_95);
ASSAULT(UK3CB_B_AssaultPack_DPM_ARID);
ASSAULT(UK3CB_B_AssaultPack_DPM_SA);
ASSAULT(UK3CB_B_AssaultPack_ERDL_AFG);
ASSAULT(UK3CB_B_AssaultPack_GRK_LIZ);
ASSAULT(UK3CB_B_AssaultPack_MAR);
ASSAULT(UK3CB_B_AssaultPack_RHB);
ASSAULT(UK3CB_B_AssaultPack_TRK);
ASSAULT(UK3CB_B_AssaultPack_VEG);
ASSAULT(UK3CB_B_AssaultPack_WDL_01);
ASSAULT(UK3CB_B_AssaultPack_WDL_02);
ASSAULT(UK3CB_B_AssaultPack_WDL_03);
ASSAULT(UK3CB_GAF_B_B_ASS_DIGI);
ASSAULT(UK3CB_GAF_B_B_ASS_MULTICAM_01);
ASSAULT(UK3CB_GAF_B_B_ASS_MULTICAM_02);
ASSAULT(UK3CB_GAF_B_B_ASS_OLI);
ASSAULT(UK3CB_GAF_B_B_ASS_TAN);
ASSAULT(UK3CB_APD_B_B_ASS_BLK_01);
ASSAULT(UK3CB_APD_B_B_ASS_BLU_01);
ASSAULT(UK3CB_APD_B_B_ASS_EKAM_BLK_01);
ASSAULT(UK3CB_APD_B_B_ASS_EKAM_BLU_01);
ASSAULT(UK3CB_ION_B_B_ASS_BLK_01);
ASSAULT(UK3CB_ION_B_B_ASS_BLK_02);
ASSAULT(UK3CB_ION_B_B_ASS_BLK_03);
ASSAULT(UK3CB_ION_B_B_ASS_BRN_01);
ASSAULT(UK3CB_ION_B_B_ASS_BRN_02);
ASSAULT(UK3CB_ION_B_B_ASS_BRN_03);
ASSAULT(UK3CB_ION_B_B_ASS_DES_01);
ASSAULT(UK3CB_ION_B_B_ASS_DES_02);
ASSAULT(UK3CB_ION_B_B_ASS_DES_03);
ASSAULT(UK3CB_ION_B_B_ASS_OLI_01);
ASSAULT(UK3CB_ION_B_B_ASS_OLI_02);
ASSAULT(UK3CB_ION_B_B_ASS_OLI_03);
ASSAULT(UK3CB_ION_B_B_ASS_WIN_01);
ASSAULT(UK3CB_ION_B_B_ASS_WIN_02);
ASSAULT(UK3CB_ION_B_B_ASS_WIN_03);
