#define KITBAG(type)\
class type: B_Kitbag_cbr {\
    maximumLoad = 280;\
}

class B_Kitbag_cbr;
KITBAG(UK3CB_B_Kitbag_DPM_68);
KITBAG(UK3CB_B_Kitbag_DPM_85);
KITBAG(UK3CB_B_Kitbag_DPM_95);
KITBAG(UK3CB_B_Kitbag_DPM_ARID);
KITBAG(UK3CB_B_Kitbag_DPM_SA);
KITBAG(UK3CB_B_Kitbag_ERDL_AFG);
KITBAG(UK3CB_B_Kitbag_GRK_LIZ);
KITBAG(UK3CB_B_Kitbag_MAR);
KITBAG(UK3CB_B_Kitbag_RHB);
KITBAG(UK3CB_B_Kitbag_TRK);
KITBAG(UK3CB_B_Kitbag_VEG);
KITBAG(UK3CB_B_Kitbag_WDL_01);
KITBAG(UK3CB_B_Kitbag_WDL_02);
KITBAG(UK3CB_B_Kitbag_WDL_03);
KITBAG(UK3CB_APD_B_B_RIF_BLK);
KITBAG(UK3CB_APD_B_B_RIF_EKAM_BLK);
KITBAG(UK3CB_APD_B_B_RIF_MED_BLK);
KITBAG(UK3CB_APD_B_B_RIF_MED_EKAM_BLK);
KITBAG(UK3CB_ION_B_B_RIF_BLK_01);
KITBAG(UK3CB_ION_B_B_RIF_BLK_02);
KITBAG(UK3CB_ION_B_B_RIF_BLK_03);
KITBAG(UK3CB_ION_B_B_RIF_BRN_01);
KITBAG(UK3CB_ION_B_B_RIF_BRN_02);
KITBAG(UK3CB_ION_B_B_RIF_BRN_03);
KITBAG(UK3CB_ION_B_B_RIF_DES_01);
KITBAG(UK3CB_ION_B_B_RIF_DES_02);
KITBAG(UK3CB_ION_B_B_RIF_DES_03);
KITBAG(UK3CB_ION_B_B_RIF_OLI_01);
KITBAG(UK3CB_ION_B_B_RIF_OLI_02);
KITBAG(UK3CB_ION_B_B_RIF_OLI_03);
KITBAG(UK3CB_ION_B_B_RIF_WIN_01);
KITBAG(UK3CB_ION_B_B_RIF_WIN_02);
KITBAG(UK3CB_ION_B_B_RIF_WIN_03);
KITBAG(UK3CB_ION_B_B_RIF_MED_BLK);
KITBAG(UK3CB_ION_B_B_RIF_MED_BRN);
KITBAG(UK3CB_ION_B_B_RIF_MED_DES);
KITBAG(UK3CB_ION_B_B_RIF_MED_OLI);
KITBAG(UK3CB_ION_B_B_RIF_MED_WIN);
KITBAG(UK3CB_KRG_B_B_FieldPack_SF_MED);
