name = "Weapons-Balance-3CBFactions"
prefix = "wb_3cbfactions"
mainprefix = "z"

[properties]
author = "johnb43"
url = "https://github.com/johnb432"

[files]
include = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
